version: '3.3'

services:
  googolplex_backend_image:
    build:
      context: .
      dockerfile: dockerfile
      target: production
    container_name: googolplex_backend
    image: johedotcom/googolplex-backend-repository:latest
    restart: always
    ports:
      - '0.0.0.0:6040:3000'
    volumes:
      - .:/usr/src/app
    command: ['node', 'dist/main.js']
    